
services:
  # 1. The Frontend (React)
  frontend:
    build: ./src/frontend
    ports:
      - "3000:80" # Maps your computer's port 3000 to Nginx's internal port 80
    depends_on:
      - app

  # 2. The Backend (Spring Boot)
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gitsandbox
    depends_on:
      - db

  # 3. The Database (PostgreSQL)
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=gitsandbox
      - POSTGRES_USER=devopsuser
      - POSTGRES_PASSWORD=devopspass
    ports:
      - "5432:5432"

  # 4. Monitoring (Nagios)
  monitoring:
    image: jasonrivers/nagios:latest
    ports:
      - "8081:80"