pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // This compiles your Java code and creates a .jar file
                bat 'mvn clean package -DskipTests'
            }
        }
        stage('Test') {
            steps {
                // Runs your JUnit tests (Requirement: >80% coverage)
                bat 'mvn test'
            }
        }
        stage('Security Scan') {
            steps {
                // Scans your Java dependencies for vulnerabilities
                bat 'trivy fs .'
            }
        }
    }
}